GAME:setValueOf("SCORE", 0)
GAME:setValueOf("LIVES", 5)
GAME:setValueOf("GAMESPEED__UPS", 11)
GAME:setValueOf("IS_PAUSED", true)
GAME:setValueOf("LOST_GAME", false)
GAME:setValueOf("LEVEL", 1)

local debounceTimer = require("luasrc/DebounceTimer") 
local energizedDebounceTimer = debounceTimer:new()
energizedDebounceTimer:setDebounceTime__sec(5)
GAME:setValueOf("ENERGIZED_TIMER", energizedDebounceTimer)